version: '3.8'

services:
  chat-client:
    env_file:
      - .env
    image: yasmany/chat-client:latest
    depends_on:
      - postgres

  chat-server:
    env_file:
      - .env
    image: yasmany/chat-server:latest
    depends_on:
      - postgres

  postgres:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    env_file:
      - .env
    image: redis:latest
    volumes:
      - red_data:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  dbgate:
    image: dbgate/dbgate
    depends_on:
      - postgres
    restart: always
    ports:
      - 8081:3000
    volumes:
      - dbgate_data:/root/.dbgate
    environment:
      CONNECTIONS: con1

      LABEL_con1: Postgres
      SERVER_con1: ${POSTGRES_HOST}
      USER_con1: ${POSTGRES_USER}
      PASSWORD_con1: ${POSTGRES_PASSWORD}
      PORT_con1: ${POSTGRES_PORT}
      ENGINE_con1: postgres@dbgate-plugin-postgres

volumes:
  pg_data:
  dbgate_data:
  red_data: {}
