version: '3.8'

services:
  chat-client:
    env_file:
      - .env
    image: yasmany/chat-client:latest
    depends_on:
      - postgres

  api:
    env_file:
      - .env
    image: yasmany/api:latest
    depends_on:
      - rabbitmq
      - mongo

  chat-server:
    env_file:
      - .env
    image: yasmany/chat-server:latest
    depends_on:
      - redis
      - rabbitmq
      - postgres

  postgres:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    env_file:
      - .env
    image: redis:latest
    volumes:
      - red_data:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    env_file:
      - .env
    image: 'mongo:6.0.2-focal'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  pg_data:
  dbgate_data:
  red_data: {}
